@startuml
:Main User: as User

(calcAverageMean)
(calcMedian)
(calcAverageMode)
(calcAverageMidRange)
(calcStdDeviation)
(calcPopulationVariance)
(calcSampleVariance)

left to right direction
User -down-> calcAverageMean
User -down-> calcMedian
User -down-> calcAverageMode
User -down-> calcAverageMidRange
User -down-> calcStdDeviation
User -down-> calcPopulationVariance
User -down-> calcSampleVariance

@enduml