site_name: DOIF With Statistics - DataObject Instantiation Framework
nav:
  - Home: index.md
  - Getting Started:
      - Setup: ./getting_started/gettingstarted00.md
      - Scenarios: ./getting_started/gettingstarted01.md
theme: readthedocs
repo_url: https://github.com/Mathiasn21/framework_project
markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true